language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="Django==1.3"
  - DJANGO="Django==1.4.2"

# command to install dependencies
install: pip install $DJANGO --use-mirrors

# command to run tests
script: ./run_tests.sh

