language: python
# python 3.7 not available for trusty
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.4"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.4"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  include:
    - name: black
      python: "3.7"
      before_script:
        - pip install black
      script: black --check --diff ordered_model/ tests/ setup.py
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install $DJANGO
  - python setup.py sdist bdist_wheel
  - pip install dist/*
  - pip install codecov
script: script/test-command
after_success:
  - codecov

deploy:
  provider: pypi
  user: "django-ordered-model"
  distributions: sdist bdist_wheel
  password:
    secure: dmhx2Z6M6k4O0pZsZ6oVpIkWf7/Vv4x36MDX35d8BmaDuD23rQZakm7ScMfHfrnJ8xTVcYsLQSciqMQyov1QfKa4/51YrJrZk63W2iAp1IjTb6FlPofbvworNcuXvEFbemYGHTeRW5S6+T6PPFN7YSJhhMJpyBIVu7rMBTk/bKE=
  on:
    tags: true
  skip_existing: true
